# Generated by Django 5.0.7 on 2024-07-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=256)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.location')),
            ],
            options={
                'unique_together': {('ingredient_name', 'location')},
            },
        ),
    ]
